# 可选的模式, 参考 gin:
#   debug
#   release
#   test
mode: debug

# web
port: 8081

# logger
log_path: /home/jdxj/workspace/words/words.log

# database
# 可选值:
#   mysql
#   sqlite
database: mysql
# sqlite
sqlite: /home/jdxj/workspace/words/words.db
# mysql
mysql:
  user: root
  pass: 123456
  addr: 127.0.0.1:3306
  base: words

# jwt
secret: 123456

# translator
# 目前只有谷歌翻译可选
translator: google