# 可选的模式, 参考 gin
# debug
# release
# test
mode: debug

# web
port: 8081

# logger
log_path: /home/jdxj/workspace/words/words.log

# sqlite
db_path: /home/jdxj/workspace/words/words.db

# jwt
secret: 123456

# translator
# 目前只有谷歌翻译可选
translator: google